---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pasj9714/public_html/kelontong/
    - /bin/cp /public/index.php $DEPLOYPATH
    - /bin/cp /public/.htaccess $DEPLOYPATH
    - /bin/cp -R /public/src $DEPLOYPATH
    - /bin/cp -R /public/themes $DEPLOYPATH
    - /bin/cp -R /public/img $DEPLOYPATH