---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pasj9714/public_html/kelontong/
    - /public/cp index.php $DEPLOYPATH
    - /public/cp .htaccess $DEPLOYPATH
    - /public/cp -R src $DEPLOYPATH
    - /public/cp -R themes $DEPLOYPATH
    - /public/cp -R img $DEPLOYPATH